import {
  AppWindow,
  AudioLines,
  Binary,
  BrainCircuit,
  Cloud,
  Code2,
  FileCode2,
  Gamepad2,
  GitBranch,
  Globe,
  Keyboard,
  MessageSquareText,
  Music,
  Orbit,
  Shapes,
  Sparkles,
  type LucideIcon,
} from 'lucide-react'

export const skillIcon: Record<string, LucideIcon> = {
  javascript: Code2,
  python: FileCode2,
  ai: BrainCircuit,
  ml: Sparkles,
  gamedev: Gamepad2,
  appdev: AppWindow,
  p5: Shapes,
  matter: Orbit,
  firebase: Cloud,
  web: Globe,
  vs: Binary,
  github: GitBranch,
  keyboard: Keyboard,
  music: Music,
  av: AudioLines,
  english: MessageSquareText,
}

export const fallbackIcon = Binary
